import Navbar from '@/components/Navbar'
import SideMenu from '@/components/SideMenu'
import { Outfit } from 'next/font/google'

const OutfitFont = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <Navbar />
      <div className='flex'>
        <SideMenu />
        {children}
      </div>
    </>
  )
}
