import './globals.css'
import { Outfit } from 'next/font/google'


const OutfitFont = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={OutfitFont.className}>
        {children}
      </body>
    </html>
  )
}
